README.md
This referenced the old MangoWeb repo.
=> Correct location to clone from

README.md
=> Updated location of GitHub Pages

_sass/base.scss, _sass/components/button.scss, _sass/components/title.scss, _sass/parts/sidebar.scss, _sass/parts/site-nav.scss, _sass/variables.scss, pages/tools/index.html
I took it upon myself to get rid of the orange color of the site, improve the shading of the menus, improve some spacing issues with the mobile version and fix an issue with the Notes column in the tools table.
=> Styling Improvements

_sass/parts/tools-table.scss
Remove fixed width to fit the table of the "tools" page.
It will adjust automatically to the upper section width.
=> Update tools-table class

README.md
bundle should run before running `bundle exec jekyll servce`
=> Need to bundle

pages/history/index.html
All modelisar pages are gone :(
=> Change Modelisar link to go to Archive.org

_posts/news/2017-11-06-FMU-Compliance_2_0_4.markdown
=> improved link to compliance checker (latest above)

CONTRIBUTING.md, _data/tools.csv
- remove links from the descriptions
- remove line breaks within rows
=> Clean up tools.csv and update contribution guide

pages/downloads.html
Fix link to Compliance Checker download until the binaries have been moved to Github https://github.com/modelica-tools/FMUComplianceChecker
=> Fix link to Compliance Checker download

pages/downloads.html
=> Update link for Compliance Checker downloads

pages/downloads.html
- add FMPy
- update tool descriptions and links
- add download and project butttons
=> Update downloads page

pages/faq.md
=> Update FAQ on FMI 3.0

pages/downloads.html
=> Re-adding link to conncted FMI 2.0 ME FMUs

pages/literature.md
=> Add missing end parentheses

pages/downloads.html
... after change of QTronic Webpage
=> Fix link to FMU-SDK

pages/faq.md
according to steering committee decision of today.
=> Changing IOV to IVA, adding numerica data types

pages/tools.html
=> Include linux32 and win32 in platform filter

pages/home.html
We have to temporarily remove the Boeing statement, until we get consent for the logo usage (cf. email from Mendo)
=> Temporarily remove Boeing statemet

pages/development.md, pages/history.md
this pull request should replace #193
=> add AVL to steering

pages/downloads.html
=> Change location of FMI 2.0 ME test FMUs

_data/tools.csv
=> Add KULI to tools.csv

CONTRIBUTING.md
The description of the platforms column is missing in CONTRIBUTING.md
=> Add description to platform column in tools.csv

pages/about.md
.. according to email communication with Andreas Junghanns.
=> Re-adding ETAS as advisory board member

pages/about.md
to googlegroups address due to forwarding problem
=> Change email address of fmi-design

pages/licenses.html
=> Redirect /licenses to /about

pages/about.md
accoding to https://github.com/modelica/fmi-standard.org/issues/182#issuecomment-612007958
=> reference MA CLA as alternative to CCLA

_data/tools.csv
For the tool TPT I changed the "available" from FMU Import-Model Exchange to FMU Import-Co-Simulation
=> TPT: FMU Import available change

pages/home.html
=> Add link to GitHub project

_posts/2020-06-16-fmi-newsletter.md, _posts/2020-06-16-newsletter.md, pages/contact.html, pages/home.html
=> Add "Subscribe to Newsletter" link

_data/tools.csv
ECU-TEST is an intuitive test tool for creating test cases for automotive software in any development phase and for their automatic execution, supporting a variety of test execution or test process tools.
=> Add ECU-TEST from TraceTronic to tools.csv

_data/tools.csv
See #292 for discussion/info, which was closed as the PR never materialised.
=> Revert 76effd3 to remove support for pandapower from tools page

pages/literature.md
Add FMI related literature from Asian Modelica Conference 2020
=> add Asian Modelica Conference

_data/cross-check/fmi2-cs-win64.csv, _data/cross-check/fmi2-me-win64.csv
Update the cross-check table on fmi-standard.org according to the Pull-Request #116 from fmi-cross-check repository from MapleSim
=> Update CrossCheck Table for MapleSim PR 116

_posts/2021-07-212-fmi3.0beta.2-prerelease.md
=> fix beta.2 prerelease post

pages/about.md
I rebased your changes onto the new master in my fork.
I think this is needed to finally get other changes merged in.
=> Fmi tm rules

pages/faq.md
- rename ports to terminals, mention separate XML file for terminals
- change order of new features (according to subjective importance, grouping changes on variables types)
=> Improve short description

assets/tools.json
Change case of SIMPACK and added CLI interface
=> Updated Simpack tool info

static/assets/tools.json
Update link and FMI versions. FYI @t-sommer @PTaeuberDS
=> Update dSPACE VEOS

static/assets/tools.json
I am part of FMI Toolbox development team from Modelon. 
FMI Toolbox supports linux platform. I also added interface details
=> Update for FMI Toolbox for Matlab/Simulink

content/tools.html, layouts/_default/single.html
=> Add link to contribution guide to tools page

static/assets/tools.json
Corrected Simcenter Webapp Server vendor
=> Update tools.json for Simcenter Webapp Server vendor

content/_index.html
=> Add three paragraph summary to front page

static/assets/tools.json
Typo on Webapp Server product name
=> Typo on Webapp Server product name

static/assets/tools.json
Fixed vendor name and updated URLs.
=> Update TLK Energy Apps in tools list

static/assets/tools.json
Hi Torsten, thank you so much for your reactivity. I forgot that one. Regards, -- 
Bruno
=> Siemens logo for SIMIT (forgot to update that one)

static/assets/tools.json
Updated with new web links and support for FMI 3.0.
=> Updated for Dassault System tools

config.yaml, content/_index.html
and remove "News" and "Events" sections
=> Add "News" nav item and latest news in masthead

CONTRIBUTING.md
Hi.
I have followed the instructions for running the website locally without thinking about. After getting some errors I figured out that the given instructions skip the submodules. I have added the command.
Timo
=> added git submodule update to the instructions for running the website locally

config.yaml, content/_index.html, content/news/_index.md
=> Update Hugo theme, use contact footer,

content/_index.html, content/about.md, content/news/2023-03-03-implementers-guide-published.md
Aligns it with spelling and wording fixes in the PR and newsletter
=> Fix IG info to match PR and spelling fixes

CONTRIBUTING.md, content/tools.html, static/assets/tools.json
=> Add "Examples & Compatibility" to tools page

config.yaml
=> Use Google Analytics 4

static/assets/tools.json
Added following 2 Siemens tools:
- Simcenter Studio
- Simcenter System Architect
=> Update tools.json with 2 tools from Siemens

static/assets/tools.json
Updated the description of Persalys in tools.json
=> Update of tools.json to add Persalys

static/assets/tools.json
Adding KOMVOS software in the list of the supporting tools
=> Add KOMVOS software in tools list

static/assets/tools.json
Adding a link to MapleSim's GitHub repo
=> Update tools.json with examplesURL

content/tools.html
=> Add SE filtering buttons to tool export

content/about.md
=> Re-add calendar

static/assets/tools.json
Updated tool information for FMI.jl
=> Updated tool information for FMI.jl

static/assets/tools.json
Source: https://github.com/modelica/fmi-standard.org/blob/b1403ea1faab75882b13dbfc16bfc35ec5cbc83e/_data/tools.csv
=> Add "source code" for more tools

static/assets/tools.json
Hello,
I have added an examplesURL line on the tools.json list for Persalys. Could you pull the changes?
Thanks!
Angélique
=> Update Persalys tool with compatibility information

static/assets/tools.json
Add Ansys System Coupling to supported tools.
=> Add Ansys System Coupling to supported tools

static/assets/tools.json
* Rename `MWorks` to `MWORKS`
* Add announcement Linux fmi3.0 supported by MWORKS tongyuan.cc
* The FMU materials in [examplesUrl](https://github.com/TongYuan-MC/fmus) has been updated
=> Update MWORKS info to the tool list

static/assets/tools.json
VendorURL was incorrect.
The VendorURL was corrected.
=> Update vendorURL for VenetDCP

static/assets/tools.json
as reported and discussed in https://github.com/modelica/fmi-standard.org/issues/586
=> Update tools.json to fix Ansys Motion reference website

content/about.md
=> Add members

static/assets/tools.json
=> Remove Rust Duplicate

static/assets/tools.json
Update LS-DYNA information with respect to vendor, url, logo
=> Update tools.json to fix Ansys LS-DYNA reference website

static/assets/tools.json
=> Update tools.json for MapleSim

static/assets/images/logos/ASTC_logo.svg, static/assets/tools.json
Update tools.json and include logo from ASTC as vendor according to contribution.md.
=> Request to include VLAB tool into FMI tools website

static/assets/tools.json
My apologies to @chrbertsch, I made a mistake when writing our website's URL! This PR fixes that.
=> collimator: fix vendor's website URL

static/assets/tools.json
- Added link to FMI Toolbox's information on export and import compatibility
- Added 3.0 version compatibility
=> Update tool information

static/assets/tools.json
Adjustments to the TwinCAT entry
=> Update tools.json - Adjustments to the TwinCAT entry

content/_index.html
=> Add links to layered standards

content/validation.html
- FMU Check performs only static checks
- put fmusim more prominently
=> Improve description on validation page

static/assets/tools.json
This adds FMI 2.0 to EnergyPlus.
=> Added EnergyPlus FMI 2.0 version

static/assets/tools.json
=> add 3.0 in gck/gcair

content/news/2024-12-03-ls-bus-rc1.md, content/news/2024-12-03-ls-struct-alpha.md, content/news/2024-12-05-Video-Slides-ASAM.md
on 
- ASAM presentation
- LS-STRUCT Alpha
- LS-BUS RC1
=> News posts

static/assets/tools.json
=> Update CPPFMU entry in tools.json

static/assets/tools.json
SIMIT supports now FMI 3.0 Co-Simulation import
=> Updated SIMIT tool description

static/assets/tools.json
adding Ansys Fluent to the list of tools supported as discussed with @chrbertsch by email
=> Add Ansys Fluent to the tools supported

static/assets/tools.json
Reverts modelica/fmi-standard.org#665
=> Revert "Remove SIM-VICUS from tools list"

static/assets/tools.json
=> YAKINDU Statechart Tools is now itemis CREATE 

static/assets/tools.json
I would like to update the description for dSPACE SCALEXIO in the FMI tools list.
=> Update dSPACE SCALEXIO description

static/assets/tools.json
ETAS Simulation Engine is a next generation of ETAS COSYM product. It is now available as a product from ETAS GmbH and support co-simulation use-cases.
=> Added ETAS Simulation Engine as new entry in tools.

static/assets/tools.json
Add FMI 2.0 support for Ansys optiSLang
=> Update tools.json (Ansys optiSLang)

static/assets/tools.json
Split the Simcenter Testlab solution in two entries. One for Simcenter Testlab Classic/Neo and one for Simcenter Testlab RT.
=> Split Simcenter Testlab solution in two entries

content/literature.md
Until we create a list of FMI related papers
=> Add link to Conference App

static/assets/tools.json
Also corrected license and vendor URL for rust-fmi
=> Updated support for export to rust-fmi

static/assets/tools.json
updated information about ecu.test
=> Update tools.json - ecu.test
