- README.md
I found that if you don't have the trailing slash, it gives you "page not found".
> Added a trailing slash

- _data/faq.yml
- pages/index.html
Since HTTPS is no longer supported with the move to GitHub Pages I've removed the https:// links
> Remove HTTPS in links to www.fmi-standard.org

- pages/faq/index.html
This is a suggestion to add a description of FMI version numbers and backwards compatibility based on the development process and an Email by Martin Otter
> Extend FAQ for versions numbers and backwards compatibility

- pages/faq/index.html
Move quote to correct position. (Heading was not shown. Full paragraph was shown in heading format)
> Fix html syntax of FAQ page

- pages/development.md
Dear FMI-Maintainer!
Please add us (Fraunhofer IEM) to the FMI Advisory Committee please.
Because we tell a many part of our reasons at the fmi meeting in roanne at okt. 2018.10.23/24.
I hope that email and my statements at fmi meeting in roanne are necessary!
Thanks for that.
Best regards
> adding Fraunhofer IEM as Advisory Committee member

- pages/development.md
synchronize group members list on fmi-standard.org to match fmi-design i.e.:
https://github.com/modelica/fmi-design/blob/master/FMI_Members/CurrentMembers.txt
> synchronize group members list

- _data/tools.csv
FMU import for co-simulation FMUs is supported since 20-sim 4.7.0 (2-03-2018), so planned should become available.
> Update 20-sim FMU import status to available

- _layouts/default.html
- _posts/2015-01-18-eight-tool-vendors.md
- _posts/2015-02-09-fmi-strategy-meeting.md
- _posts/2015-09-21-fmi-user-meeting-versailles.md
- _posts/2015-09-24-fmi-design-meeting-velizy.md
- _posts/2015-12-14-fmi-design-meeting-oberpfaffenhofen.md
- _posts/2016-06-27-fmi-design-meeting-renningen.md
- _posts/2017-05-15-fmi-user-meeting-prague.md
- _posts/2017-05-17-fmi-design-meeting-prague.md
- _posts/2017-06-13-fmi-design-meeting-paderborn.md
- _posts/2017-10-18-modelica-strategy-meeting-lund.md
- _posts/2017-11-28-fmi-design-meeting-munich.md
- _posts/2018-04-04-fmi-design-meeting-dresden.md
- _posts/2018-05-22-fmi-forum-japan.md
- _posts/2018-09-05-fmi-design-meeting-roanne.md
- _posts/2018-09-06-fmi-at-modelica-conference-americas.md
- _posts/2019-02-12-fmi-design-meeting-paderborn.md
- _posts/2019-03-04-ssp-and-dcp-standards-released.md
- _posts/2019-03-04-user-meeting-at-modelica-conference-2019.md
- _posts/2019-03-06-fmi-design-meeting-after-Modelica-Conference-Regensburg.md
- _posts/2019-04-15-FMI-Design-Meeting-Renningen.md
- _posts/2019-06-17-fmi-design-meeting-lund.md
- pages/home.html
- pages/news.html
- pages/tools.html
- add post category "events" and hide event posts
- shorten post title that breaks layout
- remove popover script from default.html
> Add Google calendar events to start page

- pages/development.md
- pages/history.md
This changes QTronic into Synopsys according to the FMI Steering Committee meeting decition Dec 16, 1019
> Reflect change from QTronic to Synopsys

- pages/development.md
- pages/history.md
This changes QTronic into Synopsys according to the FMI Steering Committee meeting decition Dec 16, 1019
!!! we need to wait for the official GO from the Steering Committee before merging this PR !!!
> Remove IFP EN from current members of FMI Steering Committee

- pages/about.md
as in FMI 2.0.1 this extension is no longer there.
> remove extension to bsd from about page

- _data/tools.csv
pandapower-fmu tool was removed due to a misleading name and link (https://github.com/modelica/fmi-standard.org/pull/234) , this is now fixed
> Add pandapower-fmu tool

- assets/tools.json
Just noticed that "GPL" isn't considered open source. License must be "osi" or "commercial".
> Changed VDMCheck license to "osi" not "GPL"

- static/assets/tools.json
Fixed the Description of the ETAS VECU-BUILDER
Software-in-the-Loop instead of Software-in-Loop
> Fix for description of ETAS VECU-BUILDER

- content/tools.html
The order of the tools should not be the order from the tools.json file. A fair ordering is a alphanumeric sorted tools list by tool name.
> Fair ordering of the tools list.

- static/assets/images/logos/casadi_logo.svg
- static/assets/tools.json
Added CasADi to the list of FMI tools. Note that the FMI export is currently FMI 3.0 only whereas FMI import is FMI 2.0 only.
> Add CasADi

- static/assets/tools.json
Added support of FMI 3.0 (co-simulation export). Amesim 2304 has been released on Friday, April 28, 2023.
> Added support for FMI 3.0 in Amesim

- static/assets/tools.json
ECU-TEST supports the versions FMI 1.0, 2.0 and 3.0, because it uses internally the library FMPy
> Update supported FMI Versions of ECU-TEST in tools.json

- CONTRIBUTING.md
(from Berlin Design Meeting)
Compatibilty information (with which other tools has FMU export and import been tested) shall replace together with a "self certification" replace the old cross check. 
Providing the compatibility information is in the sole responsibility of the tool vendors; on the FMI website tools list, only a link to an external website / repository is provided for each tool.
> Compatibility info

- static/assets/tools.json
dSPACE TargetLink now supports FMI 3.0
> FMI 3.0 by TargetLink

- static/assets/tools.json
We internally tested the SIL Kit FMU Importer with the Modelica Reference FMUs (0.0.23). As these are not our own FMUs, we did not add the examplesUrl field.
> Add SIL Kit FMU Importer to tools.json

- static/assets/tools.json
Sources: 
- https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/c-code 
- https://de.mathworks.com/help/slcompiler/gs/export-model-to-standalone-fmu-with-source-code.html
> Add C-code support for some tools

- static/assets/tools.json
VenetDCP V3.4 released in January 2024.
Please check back for updated information on VenetDCP.
> Update for VenetDCP info

- static/assets/tools.json
Hello FMI Team,
I did not see that there were a trailing space in the vendorURL of DistrictLab. Thanks for your reactivity.
Kind regards,
DistrictLab Team
> [FIX] - remove space in url for districtlab

- static/assets/tools.json
Starting CarSim2023.2, released on Sep/2023, FMU3.0 is supported on both Linux and Windows.
> Update tools.json for CarSim

- static/assets/tools.json
Add [FMIExchange.jl](https://github.com/Electa-Git/FMIExchange.jl) to the tools list. See also https://github.com/Electa-Git/FMIExchange.jl/issues/4 .
> Add FMIExchange.jl to tools

- static/assets/tools.json
FMUSDK is no longer available on Synopsys web site. I remove FMUSDK from fmi tools list too.
> Update tools.json: Synopsys removes support for FMUSDK

- static/assets/images/logos/opentwins.svg
- static/assets/tools.json
Following suggestion in:
https://github.com/ertis-research/opentwins/issues/11
We are adding OpenTwins as FMI compatible tool.
> Add OpenTwins to tools.json and logo upload

- static/assets/tools.json
Updating the tools list to reflect that fmi-library supports fmi 3.0
> Tools-list; fmi-library, added fmi 3.0 support

- static/assets/tools.json
This commit updates the URL of Vector CANape to link to an improved website.
> Update Vector CANape URL

- static/assets/images/logos/hopsan-logo.svg
- static/assets/tools.json
Added logo, improved description and added support for FMI 3.
> Update Hopsan tool information

- static/assets/tools.json
Added URL to compatibility information and example FMUs (separate link from this page).
> Add examples URL for Hopsan tool

- static/assets/tools.json
* Update section for SCADE Suite and SCADE Display according to last improvements made. 
* Add a new section for Scade One new product.
> Update sections for SCADE Tools

- static/assets/tools.json
as the linked website does not provide the required compatibility information and all provided FMUs have invalid model descriptions.
> Remove examplesURL from "fmi_adapter for ROS"

- static/assets/images/logos/fmi4c.svg
- static/assets/tools.json
Since fmi4c is a library, the compatibility cannot be directly validated. It is, however, used as a backend by the Hopsan simulation tool which does provide compatibility information. I am not sure if this information can be reused here?
> Add fmi4c to tools list

- static/assets/tools.json
Replace the urls for STC with publicly accessible URLs.
Addressing the concerns brought up in https://github.com/modelica/fmi-standard.org/pull/691 and over e-mail.
Just let me know if this suffices!
> Update tools.json for STC

- .github/workflows/gh-pages.yml
Fixing the error 
"Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/"
https://github.com/modelica/fmi-ls-bus/pull/235/files
> fix gh-pages.yml

- static/assets/images/logos/baltamatica.svg
- static/assets/tools.json
add baltamatica in tool list for importing fmus
baltamatica is a scientific computing software newly developed in China in 2020, mainly used for education and industrial simulation, we will develop the FMU exporting feature this year
> add support tool list

- static/assets/tools.json
I would like to add the dSPACE MicroLabBox II to the FMI tools list.
> Add dSPACE MicroLabBox II to tools list

- static/assets/tools.json
The MathWorks entries in the tools list are outdated and require updates. This pull request is to:
a. Add Model Exchange FMU export support for MATLAB/Simulink.
b. Add FMI 3 FMU import for Simulink Real-Time.
Thank you.
> Update MathWorks entries in the tools list
